/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.40).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.harbour.softwareengineering.springboot;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Validated
public interface InboxApi {

    @Operation(summary = "", description = "", tags={ "controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", schema = @Schema(implementation = Item.class))) })
    @RequestMapping(value = "/inbox/items",
        produces = { "application/json" },
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Item> createItem(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema())  @RequestBody Item body);


    @Operation(summary = "", description = "", tags={ "controller" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "*/*", array = @ArraySchema(schema = @Schema(implementation = Item.class)))) })
    @RequestMapping(value = "/inbox/items",
        produces = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Item>> getItems();

}

